# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73c490c298bbdbd4f0c48e03b4000e5ec86334f3be202dcf911a3265431076a230de8b5e070269a3b25b472ccb736b00fe417c2054f8d7bde6e13913627a966c

test:
  secret_key_base: 0410da56e4ddc155e88f0abf2ea5f37f9a3afd6705e7169b3e1f7a1f3777051f06798a778675b1353e43fd559fa02475a6dfa819b37b872afe9697c3e9c013b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
